[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.54"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.54"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.54"
